const ProblemsCommitState = {
  0: "Waiting",
  1: "Accepted",
  2: "Wrong Answer",
  3: "Time Exceeded",
  4: "Memory Exceeded",
  5: "Output Exceeded",
  6: "Runtime Error",
  7: "Compile Error",
  8: "System Error",
  9: "Cancelled",
  10: "Unknown Error",
  11: "Hacked",
  12: "Running",
  13: "Compiling",
  14: "Fetched",
  15: "Ignored",
  16: "Format Error",
  17: "Hack Successful",
  18: "Hack Unsuccessful",
};
export default ProblemsCommitState;
