name: Deploy Next.js Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # env:
    # 在这里添加你的环境变量
    # NEXT_PUBLIC_API_URL: https://api.aioj.net/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Archive .next folder
        run: tar -czf next-build.tar.gz .next

      - name: Copy files via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          source: "next-build.tar.gz"
          target: "/home/ubuntu/nextjs-bootstrap/"
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/ubuntu/nextjs-bootstrap
            tar -xzf next-build.tar.gz
            rm next-build.tar.gz
            pm2 restart next-app || pm2 start "npm start" --name next-app
