name: Deploy Next.js Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # env:
    # 在这里添加你的环境变量
    # NEXT_PUBLIC_API_URL: https://api.aioj.net/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Cache .next folder
        uses: actions/cache@v3
        with:
          path: .next
          key: ${{ runner.os }}-next-build-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-next-build-

      - name: Build project
        run: pnpm build

      - name: Archive multiple folders and files
        run: tar -czf build-artifacts.tar.gz .next next.config.mjs public package.json

      - name: Copy files via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          source: "build-artifacts.tar.gz"
          target: "/home/ubuntu/nextjs-bootstrap/"
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/ubuntu/nextjs-bootstrap
            tar -xzf build-artifacts.tar.gz
            rm build-artifacts.tar.gz
            pm2 restart next-app || pm2 start "npm start" --name next-app
